pip install ipython
pip install tqdm
pip install numpy
pip install pandas
pip install matplotlib
pip install seaborn
pip install scipy
pip install scikit-learn
pip install tensorflow
pip install h5py
pip install SALib
